<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ArrayCollection $units
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(ArrayCollection $units)
    {
        $entityManager = $this->getEntityManager();
        foreach ($units as $unit) {
            $entityManager->persist($unit);
        }
        $entityManager->flush();
    }
}

